# Generated by Django 2.2 on 2019-08-12 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32, verbose_name='標題')),
                ('url', models.CharField(max_length=128, verbose_name='含正則的URL')),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32, verbose_name='角色名稱')),
                ('permissions', models.ManyToManyField(blank=True, to='rbac.Permission', verbose_name='擁有的所有權限')),
            ],
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='用戶名')),
                ('password', models.CharField(max_length=64, verbose_name='密碼')),
                ('email', models.CharField(max_length=32, verbose_name='郵箱')),
                ('roles', models.ManyToManyField(blank=True, to='rbac.Role', verbose_name='擁有的所有角色')),
            ],
        ),
    ]
