# Generated by Django 2.2 on 2019-08-19 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0003_role_userinfo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userinfo',
            old_name='roles',
            new_name='role',
        ),
    ]
