# Generated by Django 2.2 on 2019-08-19 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0004_auto_20190819_2348'),
    ]

    operations = [
        migrations.RenameField(
            model_name='role',
            old_name='permissions',
            new_name='permission',
        ),
    ]
